language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
services:
  - postgres
env:
  global:
    - PGDATABASE=travis_ci_test
    - DBUSER=postgres
before_script:
  - createdb
notifications:
  email: false
